/*
 * This file was automatically generated by EvoSuite
 * Sat Apr 30 05:11:54 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      double[][] doubleArray0 = new double[4][3];
      double[][] doubleArray1 = target0.__target__(doubleArray0, 0, 1, 1, 1);
      assertEquals(2, doubleArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      double[][] doubleArray0 = new double[4][3];
      double[][] doubleArray1 = target0.__target__(doubleArray0, 1, 0, 1, 1);
      assertEquals(0, doubleArray1.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((double[][]) null, 0, 0, 0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      double[][] doubleArray0 = new double[4][3];
      // Undeclared exception!
      try { 
        target0.__target__(doubleArray0, 0, (-1387), 0, 1771);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -1386
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      double[][] doubleArray0 = new double[10][9];
      // Undeclared exception!
      try { 
        target0.__target__(doubleArray0, 1749, 1749, 1749, 1749);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1749 out of bounds for length 10
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      double[][] doubleArray0 = new double[14][9];
      double[][] doubleArray1 = target0.__target__(doubleArray0, 0, 0, 0, 0);
      assertEquals(1, doubleArray1.length);
  }
}
