/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 27 10:19:26 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[6];
      longArray0[1] = 297L;
      boolean boolean0 = target0.__target__(longArray0, 1, 1, longArray0, 0, 1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[8];
      boolean boolean0 = target0.__target__(longArray0, 0, (-898), longArray0, (-739), (-898));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[0];
      boolean boolean0 = target0.__target__(longArray0, 0, (-846), (long[]) null, 5164, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[5];
      // Undeclared exception!
      try { 
        target0.__target__((long[]) null, 1, 1, longArray0, (-3200), 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[5];
      // Undeclared exception!
      try { 
        target0.__target__(longArray0, 1, 972, longArray0, 0, 972);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 5 out of bounds for length 5
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[10];
      long[] longArray1 = new long[6];
      longArray1[1] = (long) 1;
      boolean boolean0 = target0.__target__(longArray0, 1, 1, longArray1, 1, 1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[0];
      boolean boolean0 = target0.__target__(longArray0, 1808, 1808, longArray0, 1808, 0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      long[] longArray0 = new long[10];
      boolean boolean0 = target0.__target__(longArray0, 1, 1, longArray0, 1, 1);
      assertTrue(boolean0);
  }
}
