/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 29 08:25:32 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[5];
      intArray0[0] = (-1624);
      int int0 = target0.__target__(intArray0, 0, intArray0, (-2578), Integer.MIN_VALUE);
      assertEquals(2147482836, int0);
      assertArrayEquals(new int[] {(-1624), 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[5];
      intArray0[0] = (-1624);
      int int0 = target0.__target__(intArray0, 0, intArray0, (-1624), (-1810));
      assertArrayEquals(new int[] {(-2941064), 0, 0, 0, 0}, intArray0);
      assertEquals((-3434), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((int[]) null, 2459, (int[]) null, 2459, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[8];
      intArray0[2] = (-4022);
      intArray0[3] = (-2199);
      // Undeclared exception!
      try { 
        target0.__target__(intArray0, 0, intArray0, 127, (-2165));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[3];
      int int0 = target0.__target__(intArray0, 0, intArray0, 1, Integer.MAX_VALUE);
      assertEquals(0, int0);
      assertArrayEquals(new int[] {0, 0, 0}, intArray0);
  }
}
